api/urls.py
from django.urls import path, include
from api.views import NewsViewSet

app_name = 'api'

# news 전체 보기
news_list = NewsViewSet.as_view({'get': 'list'})
# news 상세 보기
news_detail = NewsViewSet.as_view({'get': 'retrieve'})


urlpatterns = [
    path('ITnews/', news_list, name='news_list'),
    path('ITnews/<int:pk>', news_detail, name='news_detail'),
]

myPage/urls.py
from django.contrib import admin
from django.urls import path, include

from myPage.views import HomeView

# from rest_framework import routers
# from news import rest_views

# router = routers.DefaultRouter()
# router.register(r'users', rest_views.UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', HomeView.as_view(), name='home'),
    path('news/', include('news.urls', namespace='news')),

    #path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include('api.urls', namespace='api')),
]

news/urls.py
from django.urls import path
from news.views import *

app_name = 'news'

urlpatterns = [
    path('', NewsLV.as_view(), name='index'),
    path('list', GetNewsView.as_view(), name='news_list'),
    path('news/<str:pk>', NewsDV.as_view(), name='news_detail'),
    path('search/', SearchFormView.as_view(), name='search'),
  
]

api/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.


class New(models.Model):
    title = models.CharField('TITLE', max_length=300, help_text='news title')
    writer = models.CharField('WRITER', max_length=100, help_text='publisher')
    preview = models.TextField('PREVIEW', unique=True)
    published_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'new'
        verbose_name_plural = 'news'
        db_table = 'news_new'

        ordering = ('-published_date',)

    def get_previous_post(self):
        return self.get_previous_by_published_date()

    def get_next_post(self):
        return self.get_next_by_published_date()

news/forms.py
# forms.py
from django import forms


class NewsSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Keyword')
    

class GetNewsForm(forms.Form):
    pass

api/views.py
from rest_framework import viewsets
from rest_framework import permissions
from api.serializers import NewsSerializer
from news.models import New

class NewsViewSet(viewsets.ModelViewSet):
    queryset = New.objects.all()
    serializer_class = NewsSerializer
    permission_classes = [permissions.IsAuthenticated]

myPage/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = "home.html"

news/views.py
from django.views.generic import ListView, DetailView

from django.shortcuts import render
from news.models import New

from news.forms import NewsSearchForm, GetNewsForm
from django.views.generic.edit import FormView
from django.db.models import Q
import os


# Create your views here.
class NewsLV(ListView):

    model = New
    template_name = "news/news_all.html"
    context_object_name = "news"

    paginate_by = 10


class NewsDV(DetailView):
    model = New


class SearchFormView(FormView):
    form_class = NewsSearchForm  # forms.py에 생성
    template_name = "news/news_search.html"


    def form_valid(self, form):
        schword = self.request.POST['search_word']
        news_list = New.objects.filter(Q(title__icontains=schword) | Q(writer__icontains=schword) | Q(preview__icontains=schword)).distinct()

        # 검색된 결과
        context = {}

        context['form'] = form
        context['search_keyword'] = schword
        context['search_list'] = news_list

        return render(self.request, self.template_name, context)


class GetNewsView(FormView, ListView):
    template_name = "news/news_all.html"
    form_class = GetNewsForm
    success_url = '/news/list'

    model = New
    context_object_name = "news"
    paginate_by = 10


    def form_valid(self, form):
        os.chdir('/Users/toan.le/Documents/www/django-scrapy-news/myscraper')
        os.system('scrapy crawl mybot')

        return super().form_valid(form)

news/templates/news/new_detail.html
{% extends "base.html" %}
{% block title %} news : {{ object.title }} {% endblock %}

{% block content %}
<div id="content">
    <p>{{ new.published_date }}</p><br/>

    <h2> {{ object.title }}</h2>
    <p>{{ new.writer }}</p>
    <p>{{ new.preview }}</p>
   

    
</div>
{% endblock %}

news/templates/news/news_all.html
{% extends "base.html" %}
{% block title %}news List {% endblock %}

{% block content %}
<div id="content">
  <h1>IT News List</h1>

  <form action="{% url "news:news_list" %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="Crawl latest news" />
  </form><br/>
  <form action="{% url "news:search" %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="Go to Search" />
  </form><br/>

  <!-- display news list -->

  {% for new in news %}
  <h2><a href="{% url 'news:news_detail' new.id %}">
      {{ new.title }}</a></h2>
      {{ new.writer}}
      <p>{{ new.preview }}</p>
      <br/>
  {% endfor %}

  <!-- paging link -->
  <div>
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Prev</a>
    {% endif %} [ page {{ page_obj.number }} / {{page_obj.paginator.num_pages }} ]
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Next</a>
    {% endif %}
  </div>
</div>

{% endblock %}

news/templates/news/news_search.html
<!-- base 페이지 상속 -->
{% extends "base.html" %} {% block title %} 검색 페이지 {% endblock %} 
{% block content %}
<div id="content">
  <h1>News Search Engine</h1>
  <form action="" method="POST">
    <!-- CSRF 검증에 실패했습니다 -->
    <!-- CSRF 쿠키 전달 -> 요청이 위조되지 않았다! (증명)-->
    {% csrf_token %} {{ form.as_table }}
    <input type="submit" name="search" value="Search" />
  </form>
  <br /><br />
  {% if search_list %} {% for news in search_list %}
  <h3>{{news.title}}</h3>
  {{news.published_date|date:"Y-m-d"}}
  <p>{{news.writer}}</p>
  <p>{{news.preview}}</p>
  <br />
  {% endfor %} {% elif search_keyword %} [{{ search_keyword }}]의 검색 결과가 없습니다. {% endif %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
<title>{% block title %}Django Web Programming{% endblock %}</title>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static 'css/base.css' %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>

<div id="header">
    <a href="{% url 'home'%}" class="maintitle">Toan's Django Website</a>
        <h4 class="welcome">Welcome, <a href="#">OOO</a> /
            <a href="#">Change Password</a> /
            <a href="#">Logout</a>
        </h4>
</div>

<div id="menu">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li>
        <a href={% url "news:index" %}>News&bigtriangledown;</a>
    </li>
    <li><a href="{% url "news:search" %}">Search&bigtriangledown;</a>
        <ul>
            <li><a href="{% url "news:search" %}">IT</a></li>
        </ul>
    </li>
    <li><a href={% url "admin:index" %}>Admin</a></li>
</div>

{% block content %}{% endblock %}

{% block footer %}{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %} {% block title %}django website{% endblock %}
{% load static %} {% block extrastyle %}{% static 'css/home.css' %}{% endblock %}
{%block content %}
<div id="content_home">
  <div id="homeimg">
    <img src="{% static 'img/home.jpg' %}" style="height: 800px" />
    <h4 style="margin: 0">This is Toan's django website</h4>
  </div>
</div>
{% endblock %} {% block footer %}
<div id="footer">&copy; This is FOOTER Area.</div>
{% endblock %}